# Generated by Django 4.2.7 on 2023-11-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='media/slider_imgs')),
                ('Discount_Deals', models.CharField(choices=[('NEW ARRIVAL', 'NEW ARRIVAL'), ('HOT DEALS', 'HOT_DEALS'), ('FULLY DISCOUNT', 'FULLY_DISCOUNT')], max_length=200)),
                ('Quote', models.CharField(max_length=200)),
                ('Discount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider', models.ImageField(upload_to='media/slider_imgs')),
                ('Discount_Deals', models.CharField(choices=[('NEW ARRIVAL', 'NEW ARRIVAL'), ('HOT DEALS', 'HOT_DEALS'), ('FULLY DISCOUNT', 'FULLY_DISCOUNT')], max_length=200)),
                ('Sale', models.IntegerField()),
                ('Brand_name', models.CharField(max_length=200)),
                ('Discount', models.IntegerField()),
            ],
        ),
    ]
