# Generated by Django 4.2.7 on 2023-11-20 07:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_section_alter_banner_discount_deals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='Discount_Deals',
            field=models.CharField(choices=[('HOT DEALS', 'HOT_DEALS'), ('NEW ARRIVAL', 'NEW ARRIVAL'), ('FULLY DISCOUNT', 'FULLY_DISCOUNT')], max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Descriptions',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Informations',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='slider',
            name='Discount_Deals',
            field=models.CharField(choices=[('HOT DEALS', 'HOT_DEALS'), ('NEW ARRIVAL', 'NEW ARRIVAL'), ('FULLY DISCOUNT', 'FULLY_DISCOUNT')], max_length=200),
        ),
    ]
