# Generated by Django 4.2.7 on 2023-11-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_banner_discount_deals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='Discount_Deals',
            field=models.CharField(choices=[('HOT DEALS', 'HOT_DEALS'), ('FULLY DISCOUNT', 'FULLY_DISCOUNT'), ('NEW ARRIVAL', 'NEW ARRIVAL')], max_length=200),
        ),
        migrations.AlterField(
            model_name='slider',
            name='Discount_Deals',
            field=models.CharField(choices=[('HOT DEALS', 'HOT_DEALS'), ('FULLY DISCOUNT', 'FULLY_DISCOUNT'), ('NEW ARRIVAL', 'NEW ARRIVAL')], max_length=200),
        ),
        migrations.AlterModelTable(
            name='product',
            table='app_Product',
        ),
    ]
