# Generated by Django 4.2.7 on 2023-11-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_slug_alter_banner_discount_deals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='Discount_Deals',
            field=models.CharField(choices=[('FULLY DISCOUNT', 'FULLY_DISCOUNT'), ('HOT DEALS', 'HOT_DEALS'), ('NEW ARRIVAL', 'NEW ARRIVAL')], max_length=200),
        ),
        migrations.AlterField(
            model_name='slider',
            name='Discount_Deals',
            field=models.CharField(choices=[('FULLY DISCOUNT', 'FULLY_DISCOUNT'), ('HOT DEALS', 'HOT_DEALS'), ('NEW ARRIVAL', 'NEW ARRIVAL')], max_length=200),
        ),
    ]
