# Generated by Django 5.0 on 2023-12-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_banner_discount_deals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='Discount_Deals',
            field=models.CharField(choices=[('NEW ARRIVAL', 'NEW ARRIVAL'), ('HOT DEALS', 'HOT_DEALS'), ('FULLY DISCOUNT', 'FULLY_DISCOUNT')], max_length=200),
        ),
        migrations.AlterField(
            model_name='slider',
            name='Discount_Deals',
            field=models.CharField(choices=[('NEW ARRIVAL', 'NEW ARRIVAL'), ('HOT DEALS', 'HOT_DEALS'), ('FULLY DISCOUNT', 'FULLY_DISCOUNT')], max_length=200),
        ),
    ]
